oidc:
  enabled: true
  iam-properties:
    "[https://iam.recas.ba.infn.it/]":
      orchestrator:
        client-id: f63f4260-a5f0-40d2-8c85-9adb79abf220
        client-secret: JQgjPnVglg6mgNCdHCGsSy-rcypGa_HuDz1LkJKRfF56BaGjEW-9EX6BlcS5VUcfYLrAU0DRuLqqRksE36cCuQ
        scopes: ["openid", "profile", "email", "offline_access"]
      audience: "bla-bla"
      admingroup: "admins"
