version: "3"

services:
  base:
    container_name: base
    image: "mcr.microsoft.com/devcontainers/typescript-node:18"
    depends_on:
      - db_orchestrator
      - db_workflow
    environment:
      DATASOURCE_ORCHESTRATOR_NAME: ${DB_ORCHESTRATOR_NAME}
      DATASOURCE_ORCHESTRATOR_PASSWORD: ${DB_ORCHESTRATOR_PASSWORD}
      DATASOURCE_ORCHESTRATOR_URL: "jdbc:mysql://db_orchestrator:3306/${DB_ORCHESTRATOR_NAME}?allowPublicKeyRetrieval=true&useSSL=false"
      DATASOURCE_WORKFLOW_NAME: ${DB_WORKFLOW_NAME}
      DATASOURCE_WORKFLOW_PASSWORD: ${DB_WORKFLOW_PASSWORD}
      DATASOURCE_WORKFLOW_URL: "jdbc:mysql://db_workflow:3306/${DB_WORKFLOW_NAME}?allowPublicKeyRetrieval=true&useSSL=false"      
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  db_orchestrator:
    container_name: db_orchestrator
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_ORCHESTRATOR_NAME}
      MYSQL_ROOT_PASSWORD:  ${DB_ORCHESTRATOR_PASSWORD}
    volumes:
      - data_orchestrator:/var/lib/mysql

  db_workflow:
    container_name: db_workflow
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_WORKFLOW_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_WORKFLOW_PASSWORD}
    volumes:
      - data_workflow:/var/lib/mysql

volumes:
  data_orchestrator:
  data_workflow:
