version: "3"

services:
  base:
    container_name: base
    image: "mcr.microsoft.com/devcontainers/typescript-node:18"
    depends_on:
      - db
    environment:
      DATASOURCE_ORCHESTRATOR_NAME: ${DB_ORCHESTRATOR_NAME-orchestrator}
      DATASOURCE_ORCHESTRATOR_USERNAME: ${DB_ORCHESTRATOR_USERNAME-orchestrator}
      DATASOURCE_ORCHESTRATOR_PASSWORD: ${DB_ORCHESTRATOR_PASSWORD-root}
      DATASOURCE_ORCHESTRATOR_URL: "jdbc:mysql://db:3306/${DB_ORCHESTRATOR_NAME-orchestrator}?allowPublicKeyRetrieval=true&useSSL=false"
      DATASOURCE_WORKFLOW_NAME: ${DB_WORKFLOW_NAME-workflow}
      DATASOURCE_WORKFLOW_USERNAME: ${DB_WORKFLOW_USERNAME-workflow}
      DATASOURCE_WORKFLOW_PASSWORD: ${DB_WORKFLOW_PASSWORD-root}
      DATASOURCE_WORKFLOW_URL: "jdbc:mysql://db:3306/${DB_WORKFLOW_NAME-workflow}?allowPublicKeyRetrieval=true&useSSL=false"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-root}
      DB_ORCHESTRATOR_NAME: ${DB_ORCHESTRATOR_NAME-orchestrator}
      DB_ORCHESTRATOR_USERNAME: ${DB_ORCHESTRATOR_USERNAME-orchestrator}
      DB_ORCHESTRATOR_PASSWORD: ${DB_ORCHESTRATOR_PASSWORD-root}
      DB_WORKFLOW_NAME: ${DB_WORKFLOW_NAME-workflow}
      DB_WORKFLOW_USERNAME: ${DB_WORKFLOW_USERNAME-workflow}
      DB_WORKFLOW_PASSWORD: ${DB_WORKFLOW_PASSWORD-root}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

volumes:
  db_data:
