version: "3"

services:
  base:
    container_name: base
    image: "mcr.microsoft.com/devcontainers/typescript-node:18"
    depends_on:
      - db
    environment:
      DATASOURCE_ORCHESTRATOR_NAME: ${DB_ORCHESTRATOR_NAME}
      DATASOURCE_ORCHESTRATOR_USERNAME: ${DB_ORCHESTRATOR_USERNAME}
      DATASOURCE_ORCHESTRATOR_PASSWORD: ${DB_ORCHESTRATOR_PASSWORD}
      DATASOURCE_ORCHESTRATOR_URL: "jdbc:mysql://db:3306/${DB_ORCHESTRATOR_NAME}?allowPublicKeyRetrieval=true&useSSL=false"
      DATASOURCE_WORKFLOW_NAME: ${DB_WORKFLOW_NAME}
      DATASOURCE_WORKFLOW_USERNAME: ${DB_WORKFLOW_USERNAME}
      DATASOURCE_WORKFLOW_PASSWORD: ${DB_WORKFLOW_PASSWORD}
      DATASOURCE_WORKFLOW_URL: "jdbc:mysql://db:3306/${DB_WORKFLOW_NAME}?allowPublicKeyRetrieval=true&useSSL=false"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      DB_ORCHESTRATOR_NAME: ${DB_ORCHESTRATOR_NAME}
      DB_ORCHESTRATOR_USERNAME: ${DB_ORCHESTRATOR_USERNAME}
      DB_ORCHESTRATOR_PASSWORD: ${DB_ORCHESTRATOR_PASSWORD}
      DB_WORKFLOW_NAME: ${DB_WORKFLOW_NAME}
      DB_WORKFLOW_USERNAME: ${DB_WORKFLOW_USERNAME}
      DB_WORKFLOW_PASSWORD: ${DB_WORKFLOW_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  db_data:
